import { IconType } from "react-icons";

import {
    HiChevronUp,
    HiChevronDown,
    HiChevronRight,
    HiChevronLeft,
    HiOutlineArrowPath,
    HiOutlineSun,
    HiOutlineMoon,
    HiOutlineEye,
    HiOutlineEyeSlash,
    HiOutlineClipboard,
    HiOutlineMagnifyingGlass,
    HiOutlineLink,
    HiArrowUpRight,
    HiOutlineShieldCheck,
    HiOutlineSparkles,
    HiOutlineComputerDesktop,
    HiOutlineQuestionMarkCircle,
    HiOutlineInformationCircle,
    HiOutlineExclamationTriangle,
    HiOutlineExclamationCircle,
    HiOutlineCheckCircle,
    HiOutlineXMark,
    HiOutlineUser,
    HiOutlineEyeDropper,
    HiOutlineMinus,
    HiOutlinePlus,
    HiOutlineCalendar,
    HiOutlineDocumentDuplicate,
    HiOutlineCheck,
    HiOutlineArrowsPointingIn,
    HiOutlineArrowsPointingOut,
    HiOutlineChatBubbleLeftRight,
    HiOutlineHeart,
    HiOutlineFaceSmile,
    HiOutlineClock,
    HiOutlineLockClosed,
    HiOutlinePhone,
    HiOutlineEnvelope,
    HiOutlineMapPin,
    HiOutlineArrowRight,
    HiOutlinePencil,
    HiOutlineHome,
    HiOutlineArrowRightOnRectangle,
    HiOutlineSquares2X2,
    HiOutlineBars3,
    HiOutlineHandRaised,
    HiOutlineStar,
    HiOutlineCog6Tooth,
    HiOutlineShoppingBag,
    HiOutlineArrowUp,
    HiOutlineChartBarSquare,
    HiOutlineArrowTopRightOnSquare,
    HiOutlineDocument,
} from "react-icons/hi2";

import {
    RiInstagramLine,
    RiTiktokLine,
    RiGoogleFill,
    RiAppleFill,
    RiFacebookFill,
} from "react-icons/ri";
import {MdOutlineWhatsapp} from "react-icons/md";
import {FaEdit} from "react-icons/fa";
import {AiOutlineEdit} from "react-icons/ai";

export const iconLibrary: Record<string, IconType> = {
    chevronUp: HiChevronUp,
    chevronDown: HiChevronDown,
    chevronRight: HiChevronRight,
    chevronLeft: HiChevronLeft,
    refresh: HiOutlineArrowPath,
    light: HiOutlineSun,
    dark: HiOutlineMoon,
    help: HiOutlineQuestionMarkCircle,
    info: HiOutlineInformationCircle,
    warning: HiOutlineExclamationTriangle,
    danger: HiOutlineExclamationCircle,
    checkbox: HiOutlineCheck,
    check: HiOutlineCheckCircle,
    copy: HiOutlineDocumentDuplicate,
    eyeDropper: HiOutlineEyeDropper,
    clipboard: HiOutlineClipboard,
    person: HiOutlineUser,
    close: HiOutlineXMark,
    openLink: HiOutlineLink,
    arrowUpRight: HiArrowUpRight,
    arrowRight: HiOutlineArrowRight,
    minus: HiOutlineMinus,
    plus: HiOutlinePlus,
    calendar: HiOutlineCalendar,
    eye: HiOutlineEye,
    eyeOff: HiOutlineEyeSlash,
    search: HiOutlineMagnifyingGlass,
    security: HiOutlineShieldCheck,
    sparkle: HiOutlineSparkles,
    computer: HiOutlineComputerDesktop,
    minimize: HiOutlineArrowsPointingIn,
    maximize: HiOutlineArrowsPointingOut,
    chat: HiOutlineChatBubbleLeftRight,
    heart: HiOutlineHeart,
    smile: HiOutlineFaceSmile,
    clock: HiOutlineClock,
    lock: HiOutlineLockClosed,
    phone: HiOutlinePhone,
    email: HiOutlineEnvelope,
    mapPin: HiOutlineMapPin,
    instagram: RiInstagramLine,
    tiktok: RiTiktokLine,
    whatsapp: MdOutlineWhatsapp,
    google: RiGoogleFill,
    apple: RiAppleFill,
    facebook: RiFacebookFill,
    edit: AiOutlineEdit,
    home: HiOutlineHome,
    logout: HiOutlineArrowRightOnRectangle,
    grid: HiOutlineSquares2X2,
    menu: HiOutlineBars3,
    hand: HiOutlineHandRaised,
    star: HiOutlineStar,
    settings: HiOutlineCog6Tooth,
    shoppingBag: HiOutlineShoppingBag,
    sparkles: HiOutlineSparkles,
    arrowUp: HiOutlineArrowUp,
    shield: HiOutlineShieldCheck,
    chart: HiOutlineChartBarSquare,
    external: HiOutlineArrowTopRightOnSquare,
    document: HiOutlineDocument,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;